Don't define http_protocol and tls_protocol variables multiple times.
As of gcc 10, the code generator emits globals without explicit initializer
from .bss to .data, leading to:

ld: listener.o:(.rodata+0x60): multiple definition of `http_protocol'; http.o:(.data.rel.ro.local+0x0): first defined here
ld: tls.o:(.data.rel.ro.local+0x0): multiple definition of `tls_protocol'; listener.o:(.rodata+0x68): first defined here
collect2: error: ld returned 1 exit status